### PR TITLE
Allow build args "--no-manual" to affect build in addition to parameter "manual"

### PR DESCRIPTION
**Pull request by dgkf**
I'm not sure what the intended behavior is here, but it was easy enough to make a PR to illustrate the change.

I updated the build setup steps to consider both `args = "--no-manual"` as well as `manual = TRUE` when deciding whether to show message about the lack of `pdflatex`.

I discovered this issue through the use of `rcmdcheck::rcmdcheck`, and was surprised to see build messages ("pdflatex not found! Not building PDF manual.") despite passing `build_args = "--no-manual"`. I found that `rcmdcheck` calls `pkgbuild` passing `manual=TRUE`, which then uses this setup function, printing this message even if `"--no-manual"` is to be used for the build.

I just rearranged the function a bit to first build the build arguments, and use then use the build arguments as the ground-truth before printing messages. This way, either `args` or `manual` can affect the inclusion of `--no-manual` and the message will appropriately reflect the build behavior.

---

**todo:**

- [x] add tests

### CODE REVIEW

**Comment by dgkf** [comment]
I noticed today that `--no-build-vignettes` also follows similar behavior as `--no-manual`. For example

```
pkgbuild::build_setup_source(<path>, args = "--no-build-vignettes", vignettes = TRUE, clean_doc = NULL)
```

Will delete the `inst/doc` directory, and proceed to not rebuild vignettes. This is the case if the build args are provided through `rcmdcheck` which hardcodes the default of `vignettes = TRUE` and with `clean_doc` being determined by `Config/build/clean-inst-doc` in `DESCRIPTION`. 

I submitted another small patch in this PR to treat vignettes the same way, first consolidating all the flags into build arguments, and then using the build arguments as the point of truth for behaviors downstream.

**Comment by jimhester** [comment]
Great, the code and tests look good 👍

Can you please add a bullet to NEWS? It should briefly [describe the changes](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

After that I would be happy to merge this!

**Comment by jimhester** [comment]
Thanks again!

**Comment by dgkf** [comment]
Hey @jimhester - I realized I added my NEWS entry under v1.2.0. I'll add a quick PR to shuffle it over to a new version heading. Sorry to add just a bit more administration to this PR.

**Comment by jimhester** [comment]
great, thanks for catching that and for opening the new PR, sorry I missed it in my review!

**Pull request merged**
