### PR TITLE
Use errors.R from processx for better error messages

### PR DESCRIPTION
**Pull request by gaborcsardi**
* New `pkgbuild_error` class, prints the path of the package
  tree that failed, and potentially also the output.
* errors.R supports `.Last.error` and `.Last.error.trace`.

### CODE REVIEW

**Comment by jimhester** [comment]
Do you have an example of what this looks like with an installation error in a dependency?

**Comment by gaborcsardi** [comment]
pkgbuild does not install dependencies, AFAICT?

**Comment by gaborcsardi** [comment]
But this is a build error:
```
❯ pkgbuild::build("~/works/keyring", binary = TRUE)
─  installing to library ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/Rtmpne7v4j/temp_libpathffe42158de77’
─  installing *source* package ‘keyring’ ...
   ** using staged installation
   ** libs
   ccache clang -Qunused-arguments -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c keyring_macos.c -o keyring_macos.o
   keyring_macos.c:5:1: error: unknown type name 'foobar'
   foobar
   ^
   In file included from keyring_macos.c:9:
   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/types.h:78:
   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:35:
   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/i386/types.h:70:
   /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/i386/_types.h:37:1: error: expected identifier or '('
   typedef __signed char           __int8_t;
   ^
   keyring_macos.c:19:1: error: unknown type name 'foobar'
   foobar
   ^
   keyring_macos.c:21:1: error: expected identifier or '('
   void keyring_macos_error(const char *func, OSStatus status) {
   ^
   keyring_macos.c:37:32: warning: implicit declaration of function 'keyring_macos_error' is invalid in C99 [-Wimplicit-function-declaration]
     if (status != errSecSuccess) keyring_macos_error(func, status);
                                  ^
   1 warning and 4 errors generated.
   make: *** [keyring_macos.o] Error 1
   ERROR: compilation failed for package ‘keyring’
─  removing ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/Rtmpne7v4j/temp_libpathffe42158de77/keyring’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  :
  System command error
```

and then:

```
❯ .Last.error
<system_command_status_error in (function (command = NULL, args = character(), error_on_status = TRUE,  ...:
 System command error, exit status: 1, stdout + stderr (last 10 lines):
E> keyring_macos.c:21:1: error: expected identifier or '('
E> void keyring_macos_error(const char *func, OSStatus status) {
E> ^
E> keyring_macos.c:37:32: warning: implicit declaration of function 'keyring_macos_error' is invalid in C99 [-Wimplicit-function-declaration]
E>   if (status != errSecSuccess) keyring_macos_error(func, status);
E>                                ^
E> 1 warning and 4 errors generated.
E> make: *** [keyring_macos.o] Error 1
E> ERROR: compilation failed for package ‘keyring’
E> * removing ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/Rtmpne7v4j/temp_libpathffe42158de77/keyring’>
```

```
❯ .Last.error.trace

 ERROR TRACE for system_command_status_error, system_command_error, rlib_error

 1. pkgbuild::build("~/works/keyring", binary = TRUE)
 2. withr::with_temp_libpaths(rcmd_build_tools(options$cmd, c(options$path,  ...
    R/build.R:44:3
 3. base:::force(code)
 4. pkgbuild:::rcmd_build_tools(options$cmd, c(options$path, options$args),  ...
    R/build.R:44:3
 5. pkgbuild:::with_build_tools(callr::rcmd_safe(..., env = env,  ...
    R/rcmd.R:26:3
 6. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  ...
    R/rcmd.R:26:3
 7. callr:::run_r(options)
 8. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 9. base:::with.default(options, with_envvar(env, do.call(processx::run,  ...
 10. base:::eval(substitute(expr), data, enclos = parent.frame())
 11. base:::eval(substitute(expr), data, enclos = parent.frame())
 12. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmd ...
 13. base:::force(code)
 14. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 15. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 16. base:::throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command error, exit status: 1, stdout + stderr (last 10 lines):
E> keyring_macos.c:21:1: error: expected identifier or '('
E> void keyring_macos_error(const char *func, OSStatus status) {
E> ^
E> keyring_macos.c:37:32: warning: implicit declaration of function 'keyring_macos_error' is invalid in C99 [-Wimplicit-function-declaration]
E>   if (status != errSecSuccess) keyring_macos_error(func, status);
E>                                ^
E> 1 warning and 4 errors generated.
E> make: *** [keyring_macos.o] Error 1
E> ERROR: compilation failed for package ‘keyring’
E> * removing ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/Rtmpne7v4j/temp_libpathffe42158de77/keyring’
```

**Comment by jimhester** [comment]
Cool, thanks!

**Comment by jimhester** [comment]
My only concern in the standalone error.R file, maybe we should just add an rlang dependency instead?

**Comment by gaborcsardi** [comment]
Sure, that's fine as well.

**Pull request closed without merging**
